### ISSUE TITLE
"Curses" package

### ISSUE THREAD

**Issue by ghost** [AY-KE-4519/Typing-Speed-Test#1]
Is the "Curses" package Windows-only, or cross platform?
BCOZ I usually prefer cross platform over platform specific solutions.
THERE IT IS WRITTEN
`pip install windows-curses`

**Comment by Rebuk-x** [comment]
I honestly have no idea, but I do guess its platform specific. Its just a guess, but I think you need to install it on differently on different platforms.

**Comment by ghost** [comment]
Maybe this issue should be closed now.
After a month of the last comment, neither I nor you have a problem with this issue

**Comment by ghost** [comment]
Well, I understood this.

Curses is cross platform. It is there by default on Linux and Mac. But we need to get it separately for Windows.
